links:
  book: "http://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  help: "http://www.railstutorial.org/help"
  rails: "http://www.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/" 
  auth_rails: "https://www.michaelhartl.com/"
